### ISSUE TITLE
Trouble running

### ISSUE THREAD

**Issue by ympadilha** [opendilab/DI-star#10]
Hey! First of all thanks for the great project!
I just tried to run to play against the bot but I'm getting an error. Here's what I did:
- Followed the github tutorial and was able to:
- Install python 3.10.4
- Installed CUDA 11
- Installed pytorch 1.7.1
- I think I successfully downloaded the models
- Downloaded old sc2 version with the replay

Here's what I'm getting when I run:

`python -m distar.bin.play`

```
Traceback (most recent call last):
  File "C:\Users\yurim\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yurim\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\yurim\projects\di-star\distar\bin\play.py", line 86, in <module>
    actor = Actor(user_config)
  File "c:\users\yurim\projects\di-star\distar\actor\actor.py", line 38, in __init__
    self._setup_agents()
  File "c:\users\yurim\projects\di-star\distar\actor\actor.py", line 65, in _setup_agents
    state_dict = torch.load(self._cfg.model_paths[player_id], map_location='cpu')
  File "C:\Users\yurim\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\yurim\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Sorry I'm not familiar with python at all, anything I'm missing?
Thanks!

**Comment by upia99** [comment]
This is loading model file failed. Did anything went wrong when you downloaded the models? If so, you can delete *.pth files under distar/bin and redownload it.
Other possible reason maybe the version of Python or Pytorch Version.
Please try this in terminal:
python

**Comment by oneryx** [comment]
I found https://drive.google.com/file/d/1V_KdXHFhvhnZuQTWuthGEaPLQI7Ozf04/view is pretty easy to follow.
Just changed step 3, 4 with git clone this repository, didn't get any problem.

**Comment by ympadilha** [comment]
@oneryx yep I followed the drive and it worked pretty well, thank you!

@upia99 Yea I had the models downloaded, not sure what happened, but anyway with the drive it worked out, thanks!
