### ISSUE TITLE
Running into errors trying to train

### ISSUE THREAD

**Issue by szluzero** [opendilab/DI-star#14]
Hi, I am trying to train a playable the AI to learn ZvT, but am encountering some errors.

1) I made a trainingreplays folder and put some replays from Patch 4.9. Command I ran was `python -m distar.bin.sl_train --data ./trainingreplays`:
```
Start decoding replay with player 1, path: ./trainingreplays\reynorvssoul1.SC2Replay
12380 [ERROR] parse replay error SC2APIProtocol.ResponseReplayInfo.Error.InvalidReplayPath: ''
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\agent\default\replay_decoder.py", line 380, in run
    self._replay_info = self._parse_replay_info()
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\agent\default\replay_decoder.py", line 343, in _parse_replay_info
    replay_info = self._controller.replay_info(replay_path=self._replay_path)
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\pysc2\lib\remote_controller.py", line 69, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\pysc2\lib\remote_controller.py", line 60, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details))
```

2) I tried the reinforcement learning selfplay command `python -m disatr.bin.rl_train --task selfplay`. Am I understanding correctly that selfplay is when it trains by playing against me?

```
train !!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "C:\Users\Steve Lu\Downloads\miniconda\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Steve Lu\Downloads\miniconda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
TypeError: learner_run() takes 2 positional arguments but 5 were given
{'checkpoint_paths': ['C:\\Users\\Steve Lu\\Downloads\\di-star\\di-star\\experiments\\test\\league_models\\MP0H1_MP0_ckpt.pth.tar', 'C:\\Users\\Steve Lu\\Downloads\\di-star\\di-star\\experiments\\test\\league_models\\MP0_ckpt.pth.tar'], 'env_info': {'map_name': 'random', 'player_ids': ['MP0H1', 'MP0'], 'side_id': [0, 1]}, 'frac_ids': [1, 1], 'pipelines': ['default', 'default'], 'player_ids': ['MP0H1', 'MP0'], 'send_data_players': ['MP0'], 'side_ids': [0, 1], 'successive_ids': ['none', 'MP0'], 'teacher_checkpoint_paths': ['none', 'C:\\Users\\Steve Lu\\Downloads\\di-star\\di-star\\distar\\bin\\sl_model.pth'], 'teacher_player_ids': ['none', 'model'], 'update_players': ['MP0'], 'z_path': ['3map.json', '3map.json'], 'z_prob': [0.25, 0.25]}
run worker for token: MP0model at 127.0.0.1: 18992
 * Serving Flask app 'distar.ctools.worker.coordinator.coordinator' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
z_type 1 cum False bo False
Map: NewRepugnancy Race: zerg, Born location: (16, 101), loop: 4840, idx: None
Building order:
  Build_Extractor_unit, (0, 0)
  Build_SpawningPool_pt, (21, 106)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Research_ZerglingMetabolicBoost_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Build_BanelingNest_pt, (16, 111)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Build_Hatchery_pt, (16, 78)
  Train_Zergling_quick, (0, 0)
  Train_Baneling_quick, (0, 0)
  Train_Baneling_quick, (0, 0)
  Train_Queen_quick, (0, 0)
Cumulative stat:
  Build_BanelingNest_pt
  Build_Extractor_unit
  Build_Hatchery_pt
  Build_SpawningPool_pt
  Research_ZerglingMetabolicBoost_quick
  Train_Baneling_quick
  Train_Queen_quick
  Train_Zergling_quick

[EPISODE LOOP ERROR] 'terran'
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\actor\actor.py", line 140, in _inference_loop
    self.agents[idx].reset(map_name, race, game_info[idx], observations[idx])
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\agent\default\agent.py", line 191, in reset
    z = random.choice(z_data[self._map_name][self._race][born_location_str])

z_type 2 cum False bo False
Map: NewRepugnancy Race: zerg, Born location: (135, 18), loop: 9473, idx: None
Building order:
  Build_Hatchery_pt, (135, 43)
  Build_Extractor_unit, (0, 0)
  Build_SpawningPool_pt, (134, 30)
  Train_Queen_quick, (0, 0)
  Train_Queen_quick, (0, 0)
  Research_ZerglingMetabolicBoost_quick, (0, 0)
  Build_EvolutionChamber_pt, (126, 43)
  Train_Queen_quick, (0, 0)
  Research_ZergMeleeWeapons_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Train_Zergling_quick, (0, 0)
  Build_RoachWarren_pt, (125, 40)
  Build_Hatchery_pt, (104, 27)
  Build_Extractor_unit, (0, 0)
Cumulative stat:
  Build_EvolutionChamber_pt
  Build_Extractor_unit
  Build_Hatchery_pt
  Build_RoachWarren_pt
  Build_SpawningPool_pt
  Morph_Ravager_quick
  Research_ZergGroundArmor_quick
  Research_ZerglingMetabolicBoost_quick
  Research_ZergMeleeWeapons_quick
  Train_Queen_quick
  Train_Roach_quick
  Train_Zergling_quick

[EPISODE LOOP ERROR] 'terran'
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\actor\actor.py", line 140, in _inference_loop
    self.agents[idx].reset(map_name, race, game_info[idx], observations[idx])
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\agent\default\agent.py", line 191, in reset
    z = random.choice(z_data[self._map_name][self._race][born_location_str])

Process SpawnProcess-4:
Traceback (most recent call last):
  File "C:\Users\Steve Lu\Downloads\miniconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Steve Lu\Downloads\miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\bin\rl_train.py", line 153, in <module>
    actor_run(config, args)
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\bin\rl_train.py", line 65, in actor_run
Traceback (most recent call last):
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\actor\actor.py", line 140, in _inference_loop
    self.agents[idx].reset(map_name, race, game_info[idx], observations[idx])
  File "C:\Users\Steve Lu\Downloads\di-star\di-star\distar\agent\default\agent.py", line 191, in reset
    z = random.choice(z_data[self._map_name][self._race][born_location_str])
    KeyError: 'terran'
actor.run()
```

**Comment by upia99** [comment]
1.We built our agent based on versions from 4.8.2 - 4.10.0,  so only these versions and maps list [here](https://github.com/opendilab/DI-star/blob/main/distar/envs/map_info.py)  are supported now. We are working on adding support to all maps and all versions on Windows. 
2. selfplay means the agent playing against itself. The log shows 2 errors, first one(learner_run) is fixed with the new commit, please pull the new code; 2nd one comes from 'terran' is not included in the statistics Z file, we release a new training guidance please check how to generate new statistics Z file [here](https://github.com/opendilab/DI-star/blob/main/docs/guidance_to_small_scale_training.md#generate-statistics-zstrategies-file). Or you can switch back to zerg, the Reinforcement learning should be working fine.

**Comment by szluzero** [comment]
Thanks for the info! I'll read the guide and try it out when I have time

**Comment by upia99** [comment]
All maps and versions are supported now on Windows! I think it will work fine with most replays now.  need to add a few new units in some new maps i.
