### ISSUE TITLE
Running into exception when testing SL training with cuda = False

### ISSUE THREAD

**Issue by cobase2010** [opendilab/DI-star#30]
SL training works fine if I turn on cuda = True although I am running a little short of budget so I wanted to try if running on CPU works.

If I turn off cuda, here is the exception I get. Any idea how to fix this? I tried to change that part of the code to with same issue.

if torch.cuda.is_available():
                    embedding = torch.zeros(bs * shape_y * shape_x, device=x[k].device)
                    bias = torch.arange(bs, device=x[k].device).unsqueeze(dim=1) * shape_y * shape_x
                else:
                    embedding = torch.zeros(bs * shape_y * shape_x)
                    bias = torch.arange(bs).unsqueeze(dim=1) * shape_y * shape_x

[2022-12-04 14:37:58,901][checkpoint_helper.py][line: 140][    INFO] save checkpoint in /home/mark/projects/DI-star/experiments/sl_train_protoss/checkpoint/sl_train_protoss_iteration_1.pth.tar
[2022-12-04 14:37:58,902][  log_helper.py][line: 161][    INFO] BaseLearner139853483483344 save checkpoint in /home/mark/projects/DI-star/experiments/sl_train_protoss/checkpoint/sl_train_protoss_iteration_1.pth.tar
Traceback (most recent call last):
  File "/home/mark/projects/DI-star/distar/ctools/torch_utils/checkpoint_helper.py", line 364, in wrapper
    return func(*args, **kwargs)
  File "/home/mark/projects/DI-star/distar/ctools/worker/learner/base_learner.py", line 266, in run
    self._train(data)
  File "/home/mark/projects/DI-star/distar/ctools/worker/learner/base_learner.py", line 129, in wrapper
    ret = fn(*args, **kwargs)
  File "/home/mark/projects/DI-star/distar/agent/default/sl_learner.py", line 50, in _train
    logits, infer_action_info, hidden_state = self._model.sl_train(**data, hidden_state=self.hidden_state)
  File "/home/mark/projects/DI-star/distar/agent/default/model/model.py", line 182, in sl_train
    self.encoder(spatial_info, entity_info, scalar_info, entity_num)
  File "/home/mark/anaconda3/envs/distar/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mark/projects/DI-star/distar/agent/default/model/encoder.py", line 43, in forward
    embedded_spatial, map_skip = self.spatial_encoder(spatial_info, scatter_map)
  File "/home/mark/anaconda3/envs/distar/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mark/projects/DI-star/distar/agent/default/model/obs_encoder/spatial_encoder.py", line 74, in forward
    embedding[x[k].long()] = 1.
IndexError: index 9728000 is out of bounds for dimension 0 with size 9728000

**Comment by upia99** [comment]
I think it's because of data reuse in cpu, I have fixed it in new commit, please try it again

**Comment by PaParaZz1** [comment]
we have fixed this problem in this commit https://github.com/opendilab/DI-star/commit/96fbf65f4eb5f2f9fafa04f4c7d8876522ca542b

**Comment by cobase2010** [comment]
Works now.
